version: "3.8"

services:
  #  postgres:
  #    image: postgres
  #    environment:
  #      POSTGRES_USER: postgres
  #      POSTGRES_PASSWORD: sa
  #      POSTGRES_DB: SaiGonByDay
  #    ports:
  #      - "54320:5432"
  tripwonder:
    build: src/test/java/com/wiramin/learn/uploadfirmwareserver
    ports:
      - "8081:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/SaiGonByDay